### ISSUE TITLE
help me to use fuse-device

### ISSUE THREAD

**Issue by lehongwang** [MaxGraey/fuse-device#1]
I tried to include device.uno in my project but after that cannot preview
I got error

Fuse 0.30.0 (build 8529)
Build started: FullCompile
Configuring (0.7 s)
Compiling syntax tree (1.9 s)
Generating code and data
ERROR: Failed to compile .NET type 'Device': The invoked member is not supported before the type is created.
(7.0 s)

Build completed in 10.79 seconds
    1 error
Build ended
fuse: Failed to compile project
Press any key to exit.

please help

**Comment by MaxGraey** [comment]
@lehongwang What kind of operation system your preview is running? And send me please your unoproj-file

**Comment by MaxGraey** [comment]
Try to replace 
```uno 
[ForeignInclude(Language.Java, "android.app.Activity", ... ]
```
on
```uno 
[extern(Android) ForeignInclude(Language.Java, "android.app.Activity", ... ]
```

And 
```uno
[ForeignInclude(Language.ObjC, "sys/types.h", "sys/sysctl.h")]
```
on
```
[extern(iOS) ForeignInclude(Language.ObjC, "sys/types.h", "sys/sysctl.h")]
```

And see what's happening

**Comment by lehongwang** [comment]
thank you, I did it already, I worked, now testing on real iphone 6, thank you

**Comment by MaxGraey** [comment]
You are welcome. It seems issue only in Window's platform. I pushed commit for resolve this
